export const covers = {
  stalue: {
    name: "stalue",
    href: "https://stalue.com",
    project: "Stalue Machine Learning powered Stock & Crypto Value Forecasts.",
    details: "Stalue is a platform built to create and update price predictions for assets such as stocks and cryptocurrencies using the power of machine learning. The main component of the website is a stock price chart, done using ChartJS. One of the biggest challenges was to design a chart which will show current and historical prices in a clean readable way. I have done it splitting chart into two tabs. The default is a current tab showing Tesla stock price. User can also switch to historical tab and select the historical date to see previous prices on a given day. How much stock options is showed depends on the user plan. After signing up, user can buy pro tier, cancel subscription or renew it using Stripe components.",
    tech_stack: ["ReactJS", "PWA", "AWS Amplify", "Redux", "Stripe", "Material-UI", "Chart.js"],
    colors: ["#ff6060", "#4bc0c0"],
    url1: "mockup-1500x500.png",
    url2: "iPhoneXs.png",
    url3: "macbook-pro-stalue.png",
    screenshots: ["chart1.png", "chart2.png", "asset_list.png", "pricing.png",],
    logo: "/projects/stalue/logo512.svg",
  },
  bokiem: {
    name: "bokiem",
    href: "https://bokiem.solutions",
    project: "Bokiem Solutions",
    details: "Bokiem Solutions is a San Diego based company specializing in Progressive Web App development and deep expertise at running AWS-based workloads at scale.",
    tech_stack: ["ReactJS", "Redux", "Axios", "Material-UI"],
    colors: ["#5000ca", "#4bc0c0"],
    url1: "bokiem_mockup_1.png",
    url2: "desktop.png",
    url3: "mobile.png",
    logo: "/projects/bokiem/logo512.svg",
  },
  datette: {
    name: "datette",
    href: "https://datette.com",
    project: "Datette",
    colors: ["#FF9F79", "#3D444F"],
    tech_stack: ["ReactJS", "PWA", "Axios", "Material-UI", "Redux",],
    details: "Datette is a platform designed for couples to discover new date night ideas and hobby suggestions. This was one of my first projects. It is a PWA website. My goal was to make it look and work good on desktop as well as on mobile devices. In the first phase I was responsible for UI designs, creating app mockups using AdobeXD. After design approval I started coding app components with ReactJS + Material-ui library.",
    url1: "exploded_mockup_datette.png",
    screenshots: ["datette_1.png", "datette_2.png", "datette_3.png", "datette_4.png", "datette_5.png", "datette_6.png",],
  },
}